function info = getExtraDataFiles (info, validExtensions, invalidExtensions)
%function info = getExtraDataFiles (info, validExtensions,invalidExtensions)
%
% creates src and destination extra data file names (.dat .tim .tmp etc.)
% to copy to a new directory based on
% information in info (info is generated by parseDirectoryAndFileName and
% refined by createOutputFileNames)
%
% uses info.originalName and looks for associated extra data with same stub
%
% copyExtraDataFiles(info), copies (.dat .tim .tmp) files only
% copyExtraDataFiles(info, {'.a', '.b', '.c'}) copies only files with .a
% .b. .c extensions
% copyExtraDataFiles(info, [], {'.d', '.e'}) copies everything but 
%
% if validExtensions and invalidExtensions are both specified (this is
% dumb), we replace validExtensions with the set difference of
% validExtensions and invalidExtensions
%
% src and dst report the initial and final location of copied files
% this function will not overwrite existing files;  copied reports true if
% the copy was carried out successfully

if (existsAndDefault('invalidExtensions', {}))
    existsAndDefault('validExtensions', {});        
else
    existsAndDefault('validExtensions', {'.dat', '.tim', '.tmp'});
end

if (ischar(validExtensions))
    validExtensions = {validExtensions};
end

if (ischar(invalidExtensions))
    invalidExtensions = {invalidExtensions};
end

%remove the periods if any, then add them back to the beginning, making
%sure all extensions match pattern .ext
for j = 1:length(validExtensions)
    validExtensions{j} = ['.' validExtensions{j}(isstrprop(validExtensions{j}, 'alphanum'))];
end
for j = 1:length(invalidExtensions)
    invalidExtensions{j} = ['.' invalidExtensions{j}(isstrprop(invalidExtensions{j}, 'alphanum'))];
end


fs = info.fstub;
if (strcmpi(info.extension, '.mmf'))
    ind = strfind(fs, 'stack');
    if (~isempty(ind))
        fs = fs(1:(ind(end)-1));
    end
end
d = dir([fs '.*']);

for j = 1:length(d)
    [~,~,exts{j}] = fileparts(d(j).name);
end
 
exts = setdiff(exts, invalidExtensions);
if (~isempty(validExtensions))
    exts = intersect(exts, validExtensions);
end

if (isempty(exts))
    info.ext_data_src = [];
    info.ext_data_dst = [];
else
    for j = 1:length(exts)
        info.ext_data_src{j} = [fs exts{j}];
        info.ext_data_dst{j} = [info.outputstub exts{j}];
    end
end
    